module.exports = {
    alps: require('./alps'),
    button: require('./button'),
    choc: require('./choc'),
    chocmini: require('./chocmini'),
    diode: require('./diode'),
    jstph: require('./jstph'),
    jumper: require('./jumper'),
    mx: require('./mx'),
    oled: require('./oled'),
    omron: require('./omron'),
    pad: require('./pad'),
    promicro: require('./promicro'),
    promicro_flip: require('./promicro_flip'),
    rgb: require('./rgb'),
    sk6812_mini_e: require('./sk6812_mini_e'),
    rotary: require('./rotary'),
    scrollwheel: require('./scrollwheel'),
    slider: require('./slider'),
    trrs: require('./trrs'),
    via: require('./via'),
    side_switch: require('./side_switch'),
    piezo: require('./piezo'),
    oled_128x64: require('./oled_128x64'),
    d_0805: require('./d_0805'),
}